### ISSUE TITLE
转载申请

### ISSUE THREAD

**Issue by sisterAn** [yacan8/blog#32]
你好，已star，一次关于Vue的自我模拟面试和前端赋能业务 - Node实现自动化部署平台可以转载到公众号高级前端进阶上吗？会标明作者与来源，感谢

**Comment by yacan8** [comment]
> 你好，已star，一次关于Vue的自我模拟面试和前端赋能业务 - Node实现自动化部署平台可以转载到公众号高级前端进阶上吗？会标明作者与来源，感谢

可以转载的
